services:
  website:
    image: ${IMAGE_NAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mon-site.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.mon-site.entrypoints=websecure"
      - "traefik.http.routers.mon-site.tls=true"
      - "traefik.http.routers.mon-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.mon-site.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
