// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_lang_certs from "./routes/[lang]/certs.tsx";
import * as $_lang_contact from "./routes/[lang]/contact.tsx";
import * as $_lang_home from "./routes/[lang]/home.tsx";
import * as $_lang_index from "./routes/[lang]/index.tsx";
import * as $_lang_music from "./routes/[lang]/music.tsx";
import * as $_lang_projects_id_ from "./routes/[lang]/projects/[id].tsx";
import * as $_lang_projects_index from "./routes/[lang]/projects/index.tsx";
import * as $_lang_projects_site_site_ from "./routes/[lang]/projects/site/[site].tsx";
import * as $_lang_utils_colors from "./routes/[lang]/utils/colors.tsx";
import * as $_lang_utils_icons from "./routes/[lang]/utils/icons.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $AutoRegisterSection from "./islands/AutoRegisterSection.tsx";
import * as $ColorGrid from "./islands/ColorGrid.tsx";
import * as $CopyBlock from "./islands/CopyBlock.tsx";
import * as $FadeInOnVisible from "./islands/FadeInOnVisible.tsx";
import * as $IconGrid from "./islands/IconGrid.tsx";
import * as $RedirectToSection from "./islands/RedirectToSection.tsx";
import * as $ScrollArrow from "./islands/ScrollArrow.tsx";
import * as $ScrollSpyNav from "./islands/ScrollSpyNav.tsx";
import * as $SectionGroup from "./islands/SectionGroup.tsx";
import * as $SectionRegistry from "./islands/SectionRegistry.tsx";
import * as $SectionURLUpdater from "./islands/SectionURLUpdater.tsx";
import * as $SidebarNav from "./islands/SidebarNav.tsx";
import * as $SmartScrollLink from "./islands/SmartScrollLink.tsx";
import * as $TechBackground from "./islands/LogBackground.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[lang]/certs.tsx": $_lang_certs,
    "./routes/[lang]/contact.tsx": $_lang_contact,
    "./routes/[lang]/home.tsx": $_lang_home,
    "./routes/[lang]/index.tsx": $_lang_index,
    "./routes/[lang]/music.tsx": $_lang_music,
    "./routes/[lang]/projects/[id].tsx": $_lang_projects_id_,
    "./routes/[lang]/projects/index.tsx": $_lang_projects_index,
    "./routes/[lang]/projects/site/[site].tsx": $_lang_projects_site_site_,
    "./routes/[lang]/utils/colors.tsx": $_lang_utils_colors,
    "./routes/[lang]/utils/icons.tsx": $_lang_utils_icons,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
  },
  islands: {
    "./islands/AutoRegisterSection.tsx": $AutoRegisterSection,
    "./islands/ColorGrid.tsx": $ColorGrid,
    "./islands/CopyBlock.tsx": $CopyBlock,
    "./islands/FadeInOnVisible.tsx": $FadeInOnVisible,
    "./islands/IconGrid.tsx": $IconGrid,
    "./islands/RedirectToSection.tsx": $RedirectToSection,
    "./islands/ScrollArrow.tsx": $ScrollArrow,
    "./islands/ScrollSpyNav.tsx": $ScrollSpyNav,
    "./islands/SectionGroup.tsx": $SectionGroup,
    "./islands/SectionRegistry.tsx": $SectionRegistry,
    "./islands/SectionURLUpdater.tsx": $SectionURLUpdater,
    "./islands/SidebarNav.tsx": $SidebarNav,
    "./islands/SmartScrollLink.tsx": $SmartScrollLink,
    "./islands/TechBackground.tsx": $TechBackground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
